[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "functions"

[redirects]
  "/api/*" = "https://your-backend-url.netlify.app/api/:splat" [200]
